FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY my-app/package.json my-app/package-lock.json ./
COPY my-app/src ./src
COPY my-app/public ./public
RUN yarn install
RUN yarn build

# Build step #2: build the API with the client as static files
FROM python:3.9
WORKDIR /app
COPY --from=build-step /app/build ./build

RUN mkdir ./api
COPY Flask/requirements.txt Flask/App.py ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 3000
WORKDIR /app
CMD ["gunicorn", "-b", ":3000", "App:app"]